######################################################################
# Automatically generated by qmake (2.01a) ?? 22. ??? 11:00:50 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
