######################################################################
# Automatically generated by qmake (2.01a) ?? 24. ??? 10:30:43 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
